# Generated by Django 3.0.8 on 2020-07-22 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_setting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='image',
            field=models.ImageField(blank=True, default='logo.pngImagen', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='setting',
            name='user_id',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
