# Generated by Django 3.0.8 on 2020-07-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200721_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='image',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre'),
        ),
    ]
