# Generated by Django 3.0.8 on 2020-07-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200721_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='description',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='setting',
            name='phone',
            field=models.CharField(max_length=200, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='date_setting',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombres'),
        ),
    ]
